# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bcms_webdav}
  s.version = "1.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["BrowserMedia"]
  s.date = %q{2011-03-02}
  s.description = %q{Turns a BrowserCMS site into a WebDAV server, allowing access for bulk uploading files.}
  s.email = %q{github@browsermedia.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "COPYRIGHT.txt",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "doc/README_FOR_APP",
    "lib/bcms_webdav.rb",
    "lib/bcms_webdav/bcms_attachment_extensions.rb",
    "lib/bcms_webdav/file.rb",
    "lib/bcms_webdav/resource.rb",
    "lib/bcms_webdav/routes.rb",
    "lib/bcms_webdav/web_dav_middleware.rb",
    "lib/tasks/jeweler.rake",
    "public/bcms/webdav/README",
    "rails/init.rb"
  ]
  s.homepage = %q{https://github.com/browsermedia/bcms_webdav}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{browsercms}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A BrowserCMS module for WebDAV}
  s.test_files = [
    "test/performance/browsing_test.rb",
    "test/test_helper.rb",
    "test/unit/attachment_test.rb",
    "test/unit/web_dav_middleware_test.rb",
    "test/unit/web_dav_resource_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<browsercms>, [">= 3.1"])
      s.add_runtime_dependency(%q<dav4rack>, [">= 0.2.1"])
    else
      s.add_dependency(%q<browsercms>, [">= 3.1"])
      s.add_dependency(%q<dav4rack>, [">= 0.2.1"])
    end
  else
    s.add_dependency(%q<browsercms>, [">= 3.1"])
    s.add_dependency(%q<dav4rack>, [">= 0.2.1"])
  end
end

